name: Sync to Hugging Face Hub

on:
  push:
    branches: [master] # Скрипт будет запускаться при пуше в master

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Конструкция 'master:main' принудительно запишет вашу ветку master в ветку main на Hugging Face
        run: git push --force https://narxselune:$HF_TOKEN@huggingface.co/spaces/narxselune/bsac-backend master:main